# Generated by Django 5.2.3 on 2025-07-03 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('ofertante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_envio', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_limite', models.DateTimeField()),
                ('finalizada', models.BooleanField(default=False)),
                ('destino_calle', models.CharField(max_length=100)),
                ('destino_localidad', models.CharField(max_length=100)),
                ('destino_provincia', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas_creadas', to=settings.AUTH_USER_MODEL)),
                ('oferta_ganadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganadora_de', to='creacionSubastas.oferta')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='creacionSubastas.subasta'),
        ),
        migrations.CreateModel(
            name='ImagenCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cargas/')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='creacionSubastas.subasta')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSubasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('modo_cierre', models.CharField(max_length=50)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_emitidos', to=settings.AUTH_USER_MODEL)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_recibidos', to=settings.AUTH_USER_MODEL)),
                ('subasta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creacionSubastas.subasta')),
            ],
        ),
    ]
