# Generated by Django 5.2.3 on 2025-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacionSubastas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='precio_referencia',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Este es el precio que el cliente está dispuesto a pagar como máximo.', max_digits=10, verbose_name='Precio máximo dispuesto a pagar'),
        ),
    ]
