# Generated by Django 5.2.3 on 2025-07-06 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacionSubastas', '0002_subasta_precio_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
