# Generated by Django 5.2.3 on 2025-07-06 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacionSubastas', '0003_subasta_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
